title: Age Well SG
url: https://www.agewell.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#f7921e"
  secondary-color: "#ecb113"
  media-colors:
    - title: media-color-one
      color: "#e89e22"
    - title: media-color-two
      color: "#ecb455"
    - title: media-color-three
      color: "#f4c30a"
    - title: media-color-four
      color: "#f4d567"
    - title: media-color-five
      color: "#f2e2ab"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d29bdqkd4tw0cz.amplifyapp.com
prod: https://master.d29bdqkd4tw0cz.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: true
google_analytics: ""
google_analytics_ga4: G-GKKGM29669
linkedin-insights: ""
